name: Testing
on:
  push:
    branches-ignore:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: AnimMouse/setup-ffmpeg@v1
      - id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
          install-chromedriver: true
      - name: Set CHROME_PATH
        run: echo "CHROME_PATH=${{ steps.chrome.outputs.chrome-path }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install
        env:
          PUPPETEER_SKIP_DOWNLOAD: 1
      - name: Building & Testing
        run: yarn test
