name: Testing
on:
  push:
    branches-ignore:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
      - uses: FedericoCarboni/setup-ffmpeg@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Install modules
        run: yarn install
      - name: Building & Testing
        run: yarn test
